musicians = ["First Aid Kit", "Jason Molina", "Julia Jacklin", "Joanna Newsom", "Fleet Foxes", "Beach House"]
musicians.append("Lady Lamb")
print(f"I used the musicians.append('Lady Lamb') method to add Lady Lamb to the end of my musicians list:\n{musicians}\n")
musicians.insert(0, "Jessica Lea Mayfield")
print(f"I have used the musicians.insert(0, 'Jessica Lea Mayfield') method to add Jessica Lea Mayfield to the beginning of the musicians list:\n{musicians}\n")
del musicians[5]
print(f"I have used del musicians[5] to remove Fleet Foxes from my musicians list:\n{musicians}\n")
popped_musician = musicians.pop()
print(f"I have stored musicians.pop() in a variable named popped_musician. This results in the last musician in my musicians list being removed and stored in the popped_musician variable. In other words, popped_musician = '{popped_musician}'\n")
musicians.remove("Joanna Newsom")
print(f"I have used musicians.remove('Joanna Newsom') to remove the value 'Joanna Newsom' from my musicians list:\n{musicians}\n")
musicians.sort()
print(f"I have used musicians.sort() to permanatley sort my list of musicians alphabetically:\n{musicians}\n")
musicians.sort(reverse=True)
print(f"I have used the musicians.sort(reverse=True) to permanatley sore my list of musicians in reverse alphabetical order:\n{musicians}\n")
print(f"I am using sorted(musicians) to maintain the original order of my list but present it in a sorted order using print(sorted(musicians)):\n{sorted(musicians)}\n")
musicians.reverse()
print(f"I am using the musicians.reverse() function to permanently reverse the order of my musicians list:\n{musicians}\n")
print(f"I can use len(musicians) to determine that I now have {len(musicians)} musicians in my musicians list.\n")