guests = ["John", "Jack", "Tim"]
print(f"I would like to invite you to dinner, {guests[0]}.")
print(f"I would like to invite you to dinner, {guests[1]}.")
print(f"I would like to invite you to dinner, {guests[-1]}.")
print(f"Unfortunately, {guests[2]} cannot make it to dinner.")
guests[2] = "Klara"
print(f"I would like to invite you to dinner, {guests[0]}.")
print(f"I would like to invite you to dinner, {guests[1]}.")
print(f"I would like to invite you to dinner, {guests[-1]}.")
print(f"I have found a bigger table!")
guests.insert(0, "Johanna")
guests.insert(3, "Jacob")
guests.append("Walter")
print(f"I would like to invite you to dinner, {guests[0]}.")
print(f"I would like to invite you to dinner, {guests[1]}.")
print(f"I would like to invite you to dinner, {guests[2]}.")
print(f"I would like to invite you to dinner, {guests[3]}.")
print(f"I would like to invite you to dinner, {guests[4]}.")
print(f"I would like to invite you to dinner, {guests[5]}.")